spring.application.name=SportFlow
# URL de conexão com o banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/sportflow

# Credenciais de acesso do PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.validate-migration-naming=true