-- PostgreSQL / Flyway migration
-- UUIDs are generated by the application; the database enforces uniqueness.
CREATE TABLE usuario (
                         id UUID PRIMARY KEY,
                         nome VARCHAR(150) NOT NULL,
                         email VARCHAR(254) NOT NULL UNIQUE,
                         senha VARCHAR(255) NOT NULL,
                         telefone VARCHAR(30),
                         ativo BOOLEAN NOT NULL DEFAULT TRUE,
                         criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE estabelecimento (
                                 id UUID PRIMARY KEY,
                                 funcionario_id UUID,
                                 nome VARCHAR(150) NOT NULL,
                                 email VARCHAR(254) NOT NULL UNIQUE,
                                 descricao TEXT,
                                 telefone VARCHAR(30),
                                 logradouro VARCHAR(200),
                                 numero VARCHAR(20),
                                 bairro VARCHAR(100),
                                 cidade VARCHAR(100),
                                 estado CHAR(2),
                                 cep VARCHAR(9),
                                 ativo BOOLEAN NOT NULL DEFAULT TRUE,
                                 criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE funcionario (
                             id UUID PRIMARY KEY,
                             usuario_id UUID NOT NULL UNIQUE,
                             estabelecimento_id UUID NOT NULL,
                             cargo VARCHAR(100) NOT NULL,
                             data_admissao DATE NOT NULL,
                             ativo BOOLEAN NOT NULL DEFAULT TRUE,
                             criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             CONSTRAINT fk_funcionario_usuario
                                 FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE TABLE quadra (
                        id UUID PRIMARY KEY,
                        estabelecimento_id UUID NOT NULL,
                        nome VARCHAR(120) NOT NULL,
                        descricao TEXT,
                        valor_hora NUMERIC(10, 2) NOT NULL CHECK (valor_hora >= 0),
                        ativo BOOLEAN NOT NULL DEFAULT TRUE,
                        criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_quadra_estabelecimento
                            FOREIGN KEY (estabelecimento_id) REFERENCES estabelecimento (id)
);

CREATE TABLE esporte (
                         id UUID PRIMARY KEY,
                         nome VARCHAR(100) NOT NULL UNIQUE,
                         descricao TEXT,
                         criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE horario (
                         id UUID PRIMARY KEY,
                         quadra_id UUID NOT NULL,
                         esporte_id UUID NOT NULL,
                         dia_semana SMALLINT NOT NULL CHECK (dia_semana BETWEEN 0 AND 6),
                         hora_inicio TIME NOT NULL,
                         hora_fim TIME NOT NULL,
                         ativo BOOLEAN NOT NULL DEFAULT TRUE,
                         criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT ck_horario_intervalo CHECK (hora_fim > hora_inicio),
                         CONSTRAINT fk_horario_quadra FOREIGN KEY (quadra_id) REFERENCES quadra (id),
                         CONSTRAINT fk_horario_esporte FOREIGN KEY (esporte_id) REFERENCES esporte (id)
);

CREATE TABLE agendamento (
                             id UUID PRIMARY KEY,
                             usuario_id UUID NOT NULL,
                             horario_id UUID NOT NULL,
                             data_agendamento DATE NOT NULL,
                             hora_inicio TIME NOT NULL,
                             hora_fim TIME NOT NULL,
                             valor_total NUMERIC(10, 2) NOT NULL CHECK (valor_total >= 0),
                             status VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
                             observacao TEXT,
                             criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             CONSTRAINT ck_agendamento_intervalo CHECK (hora_fim > hora_inicio),
                             CONSTRAINT fk_agendamento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
                             CONSTRAINT fk_agendamento_horario FOREIGN KEY (horario_id) REFERENCES horario (id)
);

CREATE TABLE pagamento (
                           id UUID PRIMARY KEY,
                           agendamento_id UUID NOT NULL UNIQUE,
                           valor NUMERIC(10, 2) NOT NULL CHECK (valor >= 0),
                           forma VARCHAR(30) NOT NULL,
                           status VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
                           criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           pago_em TIMESTAMP WITH TIME ZONE,
                           CONSTRAINT fk_pagamento_agendamento
                               FOREIGN KEY (agendamento_id) REFERENCES agendamento (id)
);

CREATE TABLE avaliacao (
                           id UUID PRIMARY KEY,
                           agendamento_id UUID NOT NULL UNIQUE,
                           nota SMALLINT NOT NULL CHECK (nota BETWEEN 1 AND 5),
                           comentario TEXT,
                           criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           CONSTRAINT fk_avaliacao_agendamento
                               FOREIGN KEY (agendamento_id) REFERENCES agendamento (id)
);

CREATE INDEX idx_funcionario_estabelecimento_id ON funcionario (estabelecimento_id);
CREATE INDEX idx_quadra_estabelecimento_id ON quadra (estabelecimento_id);
CREATE INDEX idx_horario_quadra_id ON horario (quadra_id);
CREATE INDEX idx_horario_esporte_id ON horario (esporte_id);
CREATE INDEX idx_agendamento_usuario_id ON agendamento (usuario_id);
CREATE INDEX idx_agendamento_horario_data ON agendamento (horario_id, data_agendamento);